[package]
name = "ser_error_derive"
version = "0.1.0"
authors = ["Sergey O. Boyko <sergey.boyko0791@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
ser_error = { path = "../ser_error" }
syn = { version = "1.0", features = ["full"] }
