version: 1.0.{build}
build_script:
- cmd: marketmaker_build_etomic.cmd
cache:
  - C:\.hunter
  - marketmaker_depends
clone_depth: 5
after_build:
  - '7z a mm-win.zip
     .\build_win64_release\iguana\exchanges\Release\marketmaker-mainnet.exe
     .\marketmaker_depends\curl\build_msvc_2015_win64\lib\Release\libcurl.dll
     .\marketmaker_depends\nanomsg\build_msvc_2015_win64\Release\nanomsg.dll
     .\OSlibs\win\libsodium\Release\v140\dynamic\libsodium.dll
     "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x64\\Microsoft.VC140.CRT\\msvcp140.dll"
     "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x64\\Microsoft.VC140.CRT\\vcruntime140.dll"'

artifacts:
  - path: mm-win.zip
    name: marketmaker-mainnet

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: iabzoz73JgtOIyE/Nmz4a4XefmK+7pIeup+1Hunj4hGKrdfesFN+176DMApgfu8t
  artifact: marketmaker-mainnet
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false