[package]
name = "mm2"
version = "0.1.0"

# Waiting for https://doc.rust-lang.org/beta/cargo/reference/unstable.html#default-run to become stable.
#default-run = "mm2"

[[bin]]
name = "mm2"
path = "mm2src/mm2.rs"

[[bin]]
name = "mm2-nop"
path = "mm2src/mm2-nop.rs"
required-features = ["nop"]

[features]
# Uncomment in order to enable ETOMIC builds by default:
default = ["etomic"]
etomic = ["etomicrs"]
# Used with "mm2-nop.rs" and tells "build.rs" to skip the C build.
nop = []

[dependencies]
common = { path = "mm2src/common" }
crc = "1.8"
dirs = "1.0"
duct = "0.11"
# `etomiclibrs` pulls https://github.com/briansmith/ring, to build which on Windows we need `perl` and `yasm` in the PATH.
# Download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe and rename to `yasm.exe`.
etomicrs = { path = "mm2src/etomic", optional = true }
fomat-macros = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
fxhash = "0.2"
gstuff = "0.5"
hex = "0.3.2"
hyper = "0.12"
lazy_static = "1.1.0"
libc = "0.2"
nix = "0.11.0"
portfolio = { path = "mm2src/portfolio" }
rand = "0.5"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-core = "0.1.17"
unwrap = "1.2"
winapi = "0.3"

# ring 0.12 fails to build on Windows, this patch replaces it with ring 0.13.
[patch."https://github.com/paritytech/parity-common"]
parity-crypto = { git = "https://github.com/ArtemGr/parity-common" }
