version: '2'
services:
  seednode:
    build:
      context: ./
      dockerfile: Dockerfile.seednode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - ~/.zcash:/home/jenkins/.zcash
      - .:/usr/mm
    env_file:
      - .env.seed
    tty: true
    networks:
      default:
        ipv4_address: 10.100.0.2

  clientnode:
    build:
      context: ./
      dockerfile: Dockerfile.clientnode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - ~/.zcash:/home/jenkins/.zcash
      - .:/usr/mm
    links:
      - seednode
    tty: true
    env_file:
      - .env.client
    networks:
      default:
        ipv4_address: 10.100.0.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1