[package]
name = "common"
version = "0.1.0"
links = "marketmaker-mainnet-lib"
edition = "2018"

[lib]
name = "common"
path = "common.rs"
doctest = false

[dependencies]
backtrace = "0.3.9"
# Using the `chrono` because the `time` formatting has serious limits, like the lack of subsecond support, IIRC.
chrono = "0.4"
crossbeam = "0.6"
duct = "0.11"
eth-secp256k1 = { git = "https://github.com/ethcore/rust-secp256k1" }
fomat-macros = "0.2"
futures = "0.1"
gstuff = "0.5"
hashbrown = {version = "0.1.8", features = ["serde", "nightly"]}
hex = "0.3.2"
lazy_static = "1.2"
libc = "0.2"
hyper = "0.12"
hyper-rustls = "0.15"
rand = "0.6"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
term = "0.5"
tokio-core = "0.1"
unwrap = "1.2"

[build-dependencies]
bindgen = "0.43"
bzip2 = "0.3"
cc = "1.0"
duct = "0.11"
fomat-macros = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
glob = "0.3"
gstuff = "0.5"
hyper = "0.12"
hyper-rustls = "0.15"
itertools = "0.7.8"
libflate = "0.1"
num_cpus = "1.8.0"
regex = "1"
tar = "0.4"
unwrap = "1.2.1"
winapi = "0.3"
