[package]
name = "coins"
version = "0.1.0"
edition = "2018"

[lib]
name = "coins"
path = "lp_coins.rs"
doctest = false

[dependencies]
base64 = "0.10.0"
dirs = "1"
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
byteorder = "1.3"
bytes = "0.4"
chain = { git = "https://github.com/artemii235/parity-bitcoin.git" }
common = { path = "../common" }
ethabi = { git = "https://github.com/artemii235/ethabi" }
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1" }
ethcore-transaction = { git = "https://github.com/artemii235/parity-ethereum.git" }
ethereum-types = { version = "0.4", default-features = false, features = ["std", "serialize"] }
ethkey = { git = "https://github.com/artemii235/parity-ethereum.git" }
# Waiting for https://github.com/rust-lang/rust/issues/54725 to use on Stable.
#enum_dispatch = "0.1"
fomat-macros = "0.2"
futures = "0.1"
futures-timer = "0.1"
gstuff = "0.5"
hashbrown = {version = "0.1.8", features = ["serde", "nightly"]}
hex = "0.3.2"
hyper = "0.12"
jsonrpc-core = "8.0.1"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.3"
libc = "0.2"
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = "0.6"
rlp = { git = "https://github.com/artemii235/parity-common" }
rpc = { git = "https://github.com/artemii235/parity-bitcoin.git" }
script = { git = "https://github.com/artemii235/parity-bitcoin.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serialization = { git = "https://github.com/artemii235/parity-bitcoin.git" }
sha2 = "0.8"
sha3 = "0.8"
tokio-timer = "0.1"
tokio = "0.1.13"
# Need try_clone to shutdown and reconnect the tcp connection when there's no data received from Electrum after some time.
tokio-tcp = "=0.1.2"
unwrap = "1.2"
# One of web3 dependencies is the old `tokio-uds 0.1.7` which fails cross-compiling to ARM.
# We don't need the default web3 features at all since we added our own web3 transport using shared HYPER instance.
web3 = { git = "https://github.com/artemii235/rust-web3", default-features = false }
