[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
groestl = "0.9"
primitives = { path = "../primitives" }
ripemd160 = "0.9.0"
sha-1 = "0.9"
sha2 = "0.9"
sha3 = "0.9"
siphasher = "0.1.1"
serialization = { path = "../serialization" }
