[package]
name = "etomiclibrs"
version = "0.1.0"
authors = ["Artem Pikulin <ortgma@gmail.com>"]

[lib]
crate-type = ["staticlib"]
name = "etomiclibrs"
path = "etomiclib.rs"

[dependencies]
ethcore-transaction = { git = "https://github.com/paritytech/parity.git" }
ethkey = { git = "https://github.com/paritytech/parity.git" }
rlp = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3.1"
web3 = { git = "https://github.com/artemii235/rust-web3" }
ethabi = { git = "https://github.com/artemii235/ethabi" }
hex = "0.3.2"
regex = "1"